/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => WorkspaceLockdownPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  pinProtectionEnabled: true
};
var PIN_PROTECTION_CLASS = "workspace-lockdown-pin-protection";
var WorkspaceLockdownPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "close-tab-in-main-pane",
      name: "Close tab in main pane",
      callback: () => {
        const leaf = this.app.workspace.getMostRecentLeaf(this.app.workspace.rootSplit);
        if (leaf) {
          leaf.detach();
        }
      }
    });
    this.updatePinProtection();
    this.addSettingTab(new WorkspaceLockdownSettingTab(this.app, this));
  }
  onunload() {
    document.body.removeClass(PIN_PROTECTION_CLASS);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  updatePinProtection() {
    if (this.settings.pinProtectionEnabled) {
      document.body.addClass(PIN_PROTECTION_CLASS);
    } else {
      document.body.removeClass(PIN_PROTECTION_CLASS);
    }
  }
};
var WorkspaceLockdownSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Protect pin icons").setDesc("Disable clicking on pin icons to prevent accidentally unpinning tabs. You can still unpin via right-click menu.").addToggle((toggle) => toggle.setValue(this.plugin.settings.pinProtectionEnabled).onChange(async (value) => {
      this.plugin.settings.pinProtectionEnabled = value;
      await this.plugin.saveSettings();
      this.plugin.updatePinProtection();
    }));
  }
};
